		START	100
		LDS		#3		. INITIALIZE REGISTER S TO 3
		LDT		#30		. INITIALIZE REGISTER T TO 30
LOOP	LDX		INDEX1
		LDA		ALPHA,X	. LOAD WORD FROM ALPHA INTO REGISTER A
		LDX		INDEX2
		STA		BETA,X	. STORE WORD FROM REGISTER A INTO BETA
		LDA		INDEX1
		SUB		#3
		STA		INDEX1
		LDA		INDEX2
		ADD		#3
		STA		INDEX2
		COMPR	X,T		. COMPARE NEW X INDEX VALUE TO 30
		JLT		LOOP	. LOOP IF INDEX LESS THAN 30
		RSUB
INDEX1	WORD	27
INDEX2	WORD	0
ALPHA	WORD	93
		WORD	50
		WORD	197
		WORD	55
		WORD	96
		WORD	65
		WORD	74
		WORD	92
		WORD	43
		WORD	8
BETA	RESW	10
		END

